### ISSUE TITLE
Error when importing

### ISSUE THREAD

**Issue by m-schillinger** [frazane/scoringrules#11]
Hi Francesco, I installed scoringrules via pip and didn't receive any error, but when I try to import I receive the following error:
Do you have an idea where it comes from and how to fix it?
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/u/mschillinger/my_conda/miniconda3/envs/mlenv/lib/python3.9/site-packages/scoringrules/__init__.py", line 3, in <module>
    from scoringrules._brier import brier_score
  File "/u/mschillinger/my_conda/miniconda3/envs/mlenv/lib/python3.9/site-packages/scoringrules/_brier.py", line 3, in <module>
    from scoringrules.core import brier
  File "/u/mschillinger/my_conda/miniconda3/envs/mlenv/lib/python3.9/site-packages/scoringrules/core/brier.py", line 3, in <module>
    from scoringrules.backend import backends
  File "/u/mschillinger/my_conda/miniconda3/envs/mlenv/lib/python3.9/site-packages/scoringrules/backend/__init__.py", line 1, in <module>
    from .registry import _NUMBA_IMPORTED, BackendsRegistry
  File "/u/mschillinger/my_conda/miniconda3/envs/mlenv/lib/python3.9/site-packages/scoringrules/backend/registry.py", line 13, in <module>
    from .base import ArrayBackend
  File "/u/mschillinger/my_conda/miniconda3/envs/mlenv/lib/python3.9/site-packages/scoringrules/backend/base.py", line 11, in <module>
    class ArrayBackend(abc.ABC):
  File "/u/mschillinger/my_conda/miniconda3/envs/mlenv/lib/python3.9/site-packages/scoringrules/backend/base.py", line 27, in ArrayBackend
    dtype: Dtype | None = None,
TypeError: unsupported operand type(s) for |: 'TypeVar' and 'NoneType'
```
Thanks!

**Comment by frazane** [comment]
Hi! Thanks for reaching out. The error is due to the fact that you are using python 3.9. `scoringrules` currently supports python versions `>=3.10,<3.12`. If you can, you should update your python version to 3.10.

**Comment by m-schillinger** [comment]
Oh, thank you, I missed this.
